"""empty message

Revision ID: 6dc576e5dad5
Revises: 5eb46f326503
Create Date: 2021-07-18 23:32:29.171877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dc576e5dad5'
down_revision = '5eb46f326503'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('password', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_email_id'), 'admin', ['email_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_email_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
