"""empty message

Revision ID: 7c9338398648
Revises: 8711a45df83b
Create Date: 2021-07-22 14:01:35.379125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c9338398648'
down_revision = '8711a45df83b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email_id', sa.String(length=50), nullable=True),
    sa.Column('password_hash', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_admin_email_id'), 'admin', ['email_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_email_id'), table_name='admin')
    op.drop_table('admin')
    # ### end Alembic commands ###
