"""empty message

Revision ID: 8711a45df83b
Revises: 4c6caedce0a2
Create Date: 2021-07-22 13:55:35.273052

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8711a45df83b'
down_revision = '4c6caedce0a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.VARCHAR(length=30), nullable=True))
    # ### end Alembic commands ###
